CI: Mermaid plot

diff --git a/.github/workflows/integration-tests.yaml b/.github/workflows/integration-tests.yaml
--- a/.github/workflows/integration-tests.yaml
+++ b/.github/workflows/integration-tests.yaml
@@ -71,15 +71,12 @@ jobs:
 
   run-test:
     needs: [extract-tests, build-executable]
-    if: "always()" # Only SOME couette binaries might have failed to build
+    if: "success() || failure()" # Only SOME couette binaries might have failed to build (unless canceled)
     runs-on: minicluster
     strategy:
       fail-fast: false # If some test cases fail, still run all the others
       matrix: ${{ fromJson(needs.extract-tests.outputs.matrix) }}
     steps:
-      - name: Initialize summary
-        run: |
-          echo ':x: no test results' > "$GITHUB_STEP_SUMMARY"
       - uses: actions/checkout@v4
       - uses: actions/download-artifact@v4
         with:
@@ -116,7 +113,8 @@ jobs:
           cd build/test_cases/${{ matrix.case }}
           ../../../tools/assess-couette-flow-profile.py . > assess-couette-flow-profile.log
           cat assess-couette-flow-profile.log
-          cat assess-couette-flow-profile.log > "$GITHUB_STEP_SUMMARY"
+          cat assess-couette-flow-profile.log >> "$GITHUB_STEP_SUMMARY"
+          cat couette-flow-profile.mmd >> "$GITHUB_STEP_SUMMARY"
       - uses: actions/upload-artifact@v4
         id: artifact-upload-test-results
         with:
@@ -124,4 +122,8 @@ jobs:
           path: build/test_cases/${{ matrix.case }}      
       - name: Append test result download link to summary
         run: |
-          echo ':arrow_down: [test results](${{ steps.artifact-upload-test-results.outputs.artifact-url }})' >> "$GITHUB_STEP_SUMMARY"
+          echo '[:arrow_down: test results](${{ steps.artifact-upload-test-results.outputs.artifact-url }})' >> "$GITHUB_STEP_SUMMARY"
+      - name: Report "no test results" in summary
+        if: "failure()"
+        run: |
+          echo ':x: no test results' >> "$GITHUB_STEP_SUMMARY"
